var Crypt = {
  Jan26_2023:
    "FJMKFFKI KPW YOZKS NWZMCWSZ KR K YTU KNCOE K \nCMWON RCTPO MWR SOA EOI RDMAWSS YWDUDPO.",
  Jan24_2023:
    "BS AHUD LTODY HU H'Y TDDM VPD YRI GRAQ. H ALT \nUQLGGDXILTVDY. H MDKDX OMDA HV WRJQY YR VPLV!",
  Jan19_2023:
    "KZUCE QVJC DZEMCCA MZMOCMUE WOVAOCU EKCA V \nGCMOPAX VQE VW V DBVXZMQ GVAU JVMPSVGOPACA.",
  Jan17_2023:
    "RGGE XLO BRA DXV MOZ X GSEDRAVZOG JLSDO RV X \nEQOG, NAZ BRA'QQ JLRNXNQB VOOG ZRNRMMXV.",
  Jan12_2023:
    "CZ PSM ZCQF NKHWV KH E PXGKLEJ BMLN CZ LEFBV, CHJX \nPSM NKHW CZ SMEFPV KVH'P VGCFPKHW E UQVPELSM.",
  Jan10_2023:
    'TFSGQG NSQ "FKWYMNOQ RFGQ KSQNOTQSG," IQNRYRM \nOTQE VNRRFO KSQNOTQ OTSFPMT OTQYS IFPOTG.',
  Jan05_2023:
    'TOGF UN HRTNGL VXZZN TPEOGE UG QKKZVNG, OG \nERNE, "EK HKFQ, VLK! P\'HH VG EXPFQ NR!"',
  Jan03_2023:
    "OXBFU HSF YHS THSVFS PIFK OIF UNK, JLLK HKB FHSOI \nHTXVK BNSXKV H KFP LS YNTT JLLK.",
  Dec29_2022:
    'UQFPDZUUZ\'K HEVUF VC BQF "KBZA PZAK" REHVFK \nUERDVCFK DZYXFA, KFZJ ZCY PZJAOK KEOCYK.',
  Dec27_2022:
    "SPB UQEVQIB RUISUA QA UI UGEXIFC TXE SPB RZBBIAVUIY \nUIY IXESPBEI SBEEQSXEF UBEQUV ABEDQGBA.",
  Dec22_2022:
    "TDXTZKXHKT HW XUN RGTDNX'W GTZONWX MNWNZX. HX \nUTW GNWW XUTD XND HDKUNW CB RZNKHRHXTXHCD T QNTZ.",
  Dec20_2022:
    "DAR VUFL'K KAFUF VLR CVKAKICY HL SEUVKF YAESY? \nCFQVIYF, YEWWR, SEUVKFY DVYA IS HL YAHUF.",
  Dec15_2022:
    "XGVDBTFDIIZ NLWDETBO, LPYLETBN DBM GVRWA OGPAMN \nDAW DFVPDIIZ SAPTV. VRWZ'AW VZLWN GS XWAATWN.",
  Dec13_2022:
    "LQORUJQ JYQUG OWEXTGUJUEX VEL SZOUBUVEOYUR, \nEWJ WEQ WC JYQ IQVJKQO TVO VIKQ JW GQVL SZOUB.",
  Dec08_2022:
    "FNEZQC, CBSGQSD KIE FBUBI NOVBS BHBCBIOF VKUB IN \nHBOOBSF ZI GNCCNI PZOV OVBZS FDCJNHF.",
  Dec06_2022:
    "XG'N BMPBAN CWWK WBNA RIU VW GI RBMM BNMWWH. \nBG GJXN HIXKG X TBK OI XG PXGJ VA WAWN TMINWO.",
  Dec01_2022:
    'FDKB SRLBKE ALSJ EOK KUYLQKW, QDKZ "AVAYVOB" - \nARJDLBS VPP QDK SOVRBW FLQD ENN PVRO PKKQ.',
  Nov29_2022:
    "U EWCNUAG'O ABZ EWLSJLWG NQHHWZO ULB U KJVB\nKQD. DKBG'LB LBUHHG CUTQAV KBUSHQABO!",
  Nov22_2022:
    "LADUOXJ'C YZZR PFREYXKX FRK CFOAJR'C YZZR OUOFR \nFJX HFJPXJ OGFR OGX DHFRXO YXJBAJE.",
  Nov17_2022:
    "RSTG SYDDFDFCXKPOTO XWT PGNTWRXCTW, CSTYW \nTXWO XGN GFOCWYEO QEFOT CF JTTD CST RXCTW FPC.",
  Nov15_2022:
    "GB GQ SJBQ KY, WE UEY QIY DGEBQ DGPY ZWECLUFB \nUDQYE QIY ZYYCYTL QIY KWBQ LGDDGOJVQ?",
  Nov10_2022:
    'VTBXNW: "MAVVF, DEQ FTZ QEVN BRT HWTQTZQK?” \nKTQ: "RXT, VN?" VTBXNW: "TX, QADN MTG!"',
  Nov08_2022:
    "CYBBYNQ KJNNKGIFN JIR JTNG CTYKLGGDN. CTYKKYBE \nFQR KJERN NQGPN J PJTDYBE WGGNR JBYWJFYGB.",
  Nov03_2022:
    "OFUMFOJ EN ECO KFZ SVFJUCOCJ VUTF WFFK UHUSVFSRG, \nCKOFJHEKJRTF, RKMRNNFOFKS UKM WEOFM.",
  Nov01_2022:
    'OYLHJ PYLHWQM JQTV "URH UHWLKMYUQW" SQW OCJU Y \nVQTTYW QM URH PQMVKUKQM RH PQCTV VKWHPU KU.',
  Oct27_2022:
    "F'TA QAAE XWEPFEV W QWQD ZIG W ZAX DAWGJ, QRP UD \nXFZA WGVRAJ XFPB UA. JBA FEJFJPJ IE ZIGATAG.",
  Oct25_2022:
    'KTBBVE AHXEFG\'B EWPVGIV OTCOWV BH "BHN IBHCN," \nAUWPU WI AUN WB WGPEXFVI OH ZVVZ WGIBVTF.',
  Oct20_2022:
    "K JKZDXJKZAHAKR TDXGDXVW VUSRWXW SG DAT \nOUVZE-RARX TDXXG - KRW ZDXR DX DKW OAOZE.",
  Oct18_2022:
    "IABE TIFE GUIFOJYN LXQBO QIYV, GUB YXQB EXABE \nTQIKO GUEIFVU BQBABY JTEXMJY MIFYGEXBO.",
  Oct13_2022:
    'JANLL THLMBOFRDG, R KNNF JKODDOF, VFNLO DOLLOFJ \nLN IHJ ADNJO TFHOUG "ORFUOJL" IOPHUBVRC.',
  Oct11_2022:
    "LX RHTMJQH AV ZQQBKX EGHEAZ TG IQUEMASQ IPLRQHV. \nJQ'KK VMTB EM ITMJAIU MT ESTAZ MJQL.",
  Oct06_2022:
    'OIWS PSKBPCSS IX "OSOBWS OCPSSC": "SPXVS, TI ZIL \nHBXC CI EPBJ OIWS VMS MPSBW?" "OLPS, JSPC!"',
  Oct04_2022:
    "G LYGB NXGODYOMGQP SJCYJDYL DUY BIIDMGHH UXLLHY \nDI MHIQP USF QGHHF BOIW DUY IEEIJYJDF' CSYK.",
  Sep29_2022:
    "HDGY WX CXO LRY HDRA CXO FPXZZ GA RERNDGAY HQYD \nPDQAXFRPXZ? LRR...RERNDQAX!",
  Sep27_2022:
    "BHGEJGM, ZFH RBXIIHRZ CIXUHZ SU DJG RDIXG RMRZHB, \nSR DUIM RISVFZIM IXGVHG ZFXU HXGZF'R BDDU.",
  Sep22_2022:
    "AQS EQZGSL, ELSQJL, NQMGJQS JGMF, UGWJDMWSAMWGS \nQSX QSXLZZQ QZW MDW LSUF SQMGLSA PGMDLYM QGZRLZMA.",
  Sep20_2022:
    'Q BCLVYF IMDF WV JV TMKDF YQWV ISM AICKTIKCVA IJQI \nJMDF SQIVC. L CVGDLVF, "SVDD, FQW!"',
  Sep15_2022:
    "MDMGQMAV MLJQA GYQ DSVMDS JLUDV LEGQU L \nBQLGGRQ RLMARVUA GV XYVJ DG VXQA UQMG.",
  Sep13_2022:
    "G EPKQGVWOPKOS MIZFSMU QCM UFOECGIJ ACMI G AMIQ \nQF JMPAFKOU. LFK CFWKJ AM ZWJQ VOGVXMU.",
  Sep08_2022:
    "ZKCQ JQKJGQ NEFQ HEGLQY KT INQ ZKKT (IHQGFQ) INET \nNEFQ DQQT DKCT UT ETIECOIUOE (QGQFQT).",
  Sep06_2022:
    "OKYYNE RLP XKMP REN WIN KLMA LKL-ZSMGNEA-OKMKENP \nTNWRMZ KL WIN YNESKPSO WRDMN.",
  Sep01_2022:
    '"ECGHFA, EF\'P WGLF C DGSF MBHHWF BU SOCAPBDDCZ, \nIWFCXF." "EOCH ZFCA, XGA?" "IAFUFACMWZ AGROH DBE."',
  Aug30_2022:
    "QNIXWLPR NLWVIQ NKQ KEEIKXIS CG VLXI UCWVQ ONKG KGA \nLONIX UCPOCLGKW PNKXKPOIX. QIPLGS-VLQO: SXKPFWK.",
  Aug25_2022:
    "G BYZOFR YSEJ UMZNM CYJ BZEGJC OMGZM NZOFRM'C \nBOLEGEJ. CYJLJ NJLJ FZCB ZV LJR VFSXB.",
  Aug23_2022:
    'FZ KVD XQL FLNX-NLRRWHP HBYLR BK VRR XWGL, "CBH \nJEWUBXL" QVN NBRC BYLD QVRK V FWRRWBH IBSWLN.',
  Aug11_2022:
    "NUGE HJKJM JP VEJHRFOCV ZJ LSGMV NSGM? JJU, \nEMFHR TDSVEFJO! EUSA UGXS LSGM PSSE.",
  Aug09_2022:
    'E PVREK WLKJQPSVK YECNO SKJV E JEFLPK, PESOLO JYV \nXSKBLPO EKH OEMO, "XSFL DLLPO, ZCLEOL."',
  Aug04_2022:
    "HTILA L VTNBLG QLF BF L UGTXF DEBH KOGI L ITTP \nTROF MTP QO. B HKTECKH, XKLH L FBUO VODHOP.",
  Aug02_2022:
    'TLTJU QKNSXNC SBANXNUQ GQ SGKHSNVTX "QBVTZOGSD-\nDNZT," GVICUGSD ZONZ ANZTJDNZT ANQ NFBEZ ANZTJ.',
  Jul28_2022:
    'ABRP CDC KRZ-F KXEWMRNMZ ERMM BDG HDNMJNDVUC \nLVJXNV PBVDN AVCCDUH? BDG "JVZXUEV."',
  Jul26_2022:
    "CZCDHC GYU YGZV NCD UNS ZYGPSDU OYCDUZMGS, MU \nNCD IYWS OYCDU UNCG STSWV YUNSW DUCUS OYIRMGSX.",
  Jul21_2022:
    '"EKLOW" EZK "EKLDT" UDVC YOEZ, QLVOMEQQB, "VD PDK," \nJCLQO "PDDKUBO" LT TCDMV IDM "PDK UO JLVC BO."',
  Jul19_2022:
    "BJTL GZ AZD VTEE T CZVS ICZDQ BJZMN RZDC RTWZDM \nWNWXNCM GZY'L MPYI? WZDYL CDMJWZCN.",
  Jul14_2022:
    "PVF CXPPXZ XQ HBUF FLKF KI VKEVFL PVBO PVF INLQBJF \nXQ OFBLCD HBUF XOPBLKX.",
  Jul12_2022:
    "TMQ WZ LWV VMUAMDLO OUZMTV' RDQQJFZMVQ QAAQOW, \nNQJMV LV WFQ FZWWQVW HUEJQW LJ ZMD VZUED VIVWQX.",
  Jul07_2022:
    'DTX GPJZ "RTXRELMDX" RPLXV NJPL DTX CXJVOMH \n"VTMT LMD," GTORT LXMHV "DTX EOHY OV ZXMZ."',
  Jul05_2022:
    "YGF IEUYFJWFU SP RFUY-UFAAWDC HXYGSJ HCHYGH \nQGJWUYWF GHBF USAO LFAA SBFJ YLS RWAAWSD QSVWFU.",
  Jun30_2022:
    "AYVSOVX YKUYVBYMSYD FYAUYVNFOVY DEBMWD GL \nGHYV N FPGODNMT TYWVYYD LNPVYMPYBF.",
  Jun28_2022:
    "HBZWREOPFA XWPW OYHW NJ PWAGEW NUW FPJXSBSR \nUBQQBW WDWS NUJERU UW XOA QPWNNC ZOP JEN.",
  Jun23_2022:
    "GZYSJPV'D FVPRJ VPI DYLJ SD R DJLVU KRVFPV JARB \nPRVJA JARJ ARD VRFPI QLV AZBIVPID LQ NPRVD.",
  Jun21_2022:
    'IXTOV EKVTOVJY UKV GUMMVZ "CKUOMVKY" SVGUHYV \nCPVN JVKV XKOWODUMMN YPXJD URCVK CPV RVUCHKV.',
  Jun16_2022:
    "O'TT STYSDE FSXC S EZCVOST ZTSVC OU BD FCSJR KNJ \nBD OURCJXCURJOVITSJ ECZRIB.",
  Jun14_2022:
    "XRVXFM, FCN MDAT, HJ LZC DFRM JLXLC EXWHLXR LZXL \nCFGJ HF HLJ DNF JLXLC'J WDJLXR XVVACOHXLHDF.",
  Jun09_2022:
    "FJK ZENNWIV TFEIKT FEEH FJKWZ IRYK OZEY R TEIV UG \nPJWPRVE UNBKTYRI YBSSG XRFKZT.",
  Jun07_2022:
    "MJHT PYHE B UHXKVBU NYOH WKUT RTWY B PBP NYOH? \nMJHT RW FHGYDHE BCCBUHTW.",
  Jun02_2022:
    'L AKLVP JPZZQ TKVRYKQQ RZJONKFZJ KPJ PLJPZ KV \nNIOU YBJKO: "K\'Y L FKA YZPLQ GLV".',
  May31_2022:
    "GXI XTAXIJG VQO USLIJG CSTQGJ TQ GXI PSQGTQIQGVU \nFQTGIO JGVGIJ VNI MSGX TQ TQBS PSFQGB, PVUTHSNQTV.",
  May24_2022:
    "NUWWPOQU UW JGC PZFX WJVJC JGVJ EPQLCQW VW NVZX \nPJGCQ WJVJCW VW UJ GVW FCJJCQW UZ UJW ZVNC.",
  May19_2022:
    "YAKOXKENCH XG KGVXPGE CNZP RPCP JKXO EN \nPGONCHP VNZZPCVXKA JCNOTVEH.",
  May17_2022:
    "UXIZFDNVW IHS TFDE AQS YV TFNZSDYW FD YGS \nZFLHVWLVTFL IXNIS IDA RHFDS WGHFZT YGIY YGSP SIY.",
  May12_2022:
    "JCB OBXJHBV DBXNHS NBEDFJBL XJ BNFK KHXTJMD'V \nABLLFDP, ACBNB XHH OEJ RMCD HBDDMD THXSBL.",
  May10_2022:
    "R TFIY F LSRHHPREB XYFS GX YPYIFUGSC, CG R'IY \nCUFSUYK UFMREB CUYHC UG FIGRK UTYN.",
  May05_2022:
    "FRPM FCVPI JO WTJEPK JM XPIT NICBJVL, VRP BCDTI YTIAO \nC ECINP WHWWEP CMK UEJMNO VT VRP RPCV OTHIUP.",
  May03_2022:
    "PVC GOROCLTWCLWT KWN XVR PVC QPF PT HLCRK \nUPTRCPZ. LR'N XWCR PJ WT WTRL-ZLRROC UWDXWLFT.",
  Apr28_2022:
    "AJC JQGBP, N R-YJNOCP XGLC LCNI AJC AGLHRC, BY AJC \nGLKQ JRZNL XGLC LGA TGLLCTACP AG NLGAJCI.",
  Apr26_2022:
    "(NGN HPLF GRFVY.) BPQ NPFU YBF AGD KD YBF APPD \nWFY BKU BGKV TOY? FTRKJUF KY.",
  Apr21_2022:
    "CFU-HDFLHA FC HDR QRCH JICCFQWR HFVR IK O \nLRNZWOL OKOWIN GWIGB - DOKYC YIPK.",
  Apr19_2022:
    "EAT CLXM 'TVSLC' TJQYETM STHLXT YADBTYGTDXT, SOE \nAQY QY EAT HQXYE BPLCP OYT LH QE DY D ZTXS.",
  Apr14_2022:
    "HGQYORNFGJ, NJ TDDTJIGNR Q FGINSGJ, END \nYHGMGJNRRW PNRRTL RNPIYPUHYST NJL IUTJ FGINSGJ M.",
  Apr12_2022:
    "SPMVEKF URB ITUUTD TW M RTU UJMX TW IJTHKEBO EK \nEVB HMUBJ HEPP DMCB URBD BZUJM JEVR MKN WQNFX.",
  Apr07_2022:
    "BSO QGOOMN AWHEBOGFYR DYE YVVJEOM WU XGWFWBZRQ \nSZE WDR ESOAAUZES ZRBOGOEBE.",
  Apr05_2022:
    "MOH WJBY ARXR'V GRJP PYIXV PHZPHVHIM XHPQWI \nWJMRQWEHPV MOWM QHPXHB MR GRPQ RIH KRQZWIF.",
  Mar15_2022:
    "XD IZBXO GQDDJO SXE DIP ZJMM X ZPXPTJPPJ UJRIOJ \nIRRJOQDC QP PI PKJ XBXLJSE RIO X LIMMXO.",
  Mar31_2022:
    "JLXNXY, GPCY'Y KDDUC GXXD, KY P GXYSMV WPCZ-FCPV \nXNTUQS YLPJUW MKZU P JXSPSX.",
  Mar29_2022:
    "ZCS GNVV FVGFZK KUFZ ZCSBL NH ZCS LPU POPEMNKP,\nPFU XECXPEVZ FBJ VNP FRCSU ZCSE FLP.",
};
var Solutions = {
  Jan26_2023:
    "MUHAMMAD ALI BEGAN FIGHTING AS A BOY AFTER A \nTHIEF STOLE HIS NEW RED SCHWINN BICYCLE.",
  Jan24_2023:
    "MY WIFE ASKED IF I'D SEEN THE DOG BOWL. I WAS\nFLABBERGASTED. I NEVER KNEW IT COULD DO THAT!",
  Jan19_2023:
    "VIDEO GAME PIONEER NINTENDO STARTED OVER A \nCENTURY AGO AS A PLAYING CARD MANUFACTURER.",
  Jan17_2023:
    "ODDS ARE YOU CAN GET A DISCOUNTED PRICE ON A \nSLED, BUT YOU'LL PROBABLY NEED TOBOGGAN.",
  Jan12_2023:
    "OF THE FOUR KINGS IN A TYPICAL DECK OF CARDS, ONLY \nTHE KING OF HEARTS ISN'T SPORTING A MUSTACHE.",
  Jan10_2023:
    'HORSES ARE "OBLIGATE NOSE BREATHERS," MEANING \nTHEY CANNOT BREATHE THROUGH THEIR MOUTHS.',
  Jan05_2023:
    'WHEN MY LAWYER BUDDY WISHES ME GOODBYE, HE \nSAYS, "SO LONG, BRO! I\'LL BE SUING YA!"',
  Jan03_2023:
    "TIDES ARE FAR LARGER WHEN THE SUN, MOON AND EARTH \nALIGN DURING A NEW OR FULL MOON.",
  Dec29_2022:
    'CHEWBACCA\'S VOICE IN THE "STAR WARS" MOVIES \nCOMBINES BADGER, SEAL AND WALRUS SOUNDS.',
  Dec27_2022:
    "THE AIRLINE QANTAS IS AN ACRONYM FOR THE QUEENSLAND \nAND NORTHERN TERRITORY AERIAL SERVICES.",
  Dec20_2022:
    "WHY AREN'T THERE ANY BATHTUBS ON PIRATE SHIPS? \nBECAUSE, SILLY, PIRATES WASH UP ON SHORE.",
  Dec15_2022:
    "BOTANICALLY SPEAKING, PUMPKINS AND OTHER GOURDS \nARE ACTUALLY FRUIT. THEY'RE TYPES OF BERRIES.",
  Dec13_2022:
    "DESPITE THEIR SONGWRITING AND MUSICIANSHIP, \nNOT ONE OF THE BEATLES WAS ABLE TO READ MUSIC.",
  Dec08_2022:
    "SODIUM, MERCURY AND SEVEN OTHER ELEMENTS HAVE NO \nLETTERS IN COMMON WITH THEIR SYMBOLS.",
  Dec06_2022:
    "IT'S ALWAYS BEEN EASY FOR ME TO FALL ASLEEP. \nAT THIS POINT I CAN DO IT WITH MY EYES CLOSED.",
  Dec01_2022:
    'WHEN GUINEA PIGS ARE EXCITED, THEY "POPCORN" - \nPUSHING OFF THE GROUND WITH ALL FOUR FEET.',
  Nov29_2022:
    "A COMPANY'S NEW CORDUROY PILLOWS ARE A HUGE \nHIT. THEY'RE REALLY MAKING HEADLINES!",
  Nov22_2022:
    "JUPITER'S MOON GANYMEDE AND SATURN'S MOON TITAN \nARE LARGER THAN THE PLANET MERCURY.",
  Nov17_2022:
    "WHEN HIPPOPOTAMUSES ARE UNDERWATER, THEIR \nEARS AND NOSTRILS CLOSE TO KEEP THE WATER OUT.",
  Nov15_2022:
    "IS IT JUST ME, OR ARE THE FIRST FIVE WORKDAYS \nAFTER THE WEEKEND THE MOST DIFFICULT?",
  Nov10_2022:
    'MOTHER: "JIMMY, CAN YOU NAME TWO PRONOUNS?” \nSON: "WHO, ME?" MOTHER: "OH, NICE JOB!"',
  Nov08_2022:
    "FINNISH PASSPORTS ARE ALSO FLIPBOOKS. FLIPPING \nTHE PAGES SHOWS A WALKING MOOSE ANIMATION.",
  Nov03_2022:
    "READERS OF OUR NEW THESAURUS HAVE BEEN APATHETIC, \nUNRESPONSIVE, INDIFFERENT AND BORED.",
  Nov01_2022:
    'JAMES CAMERON SOLD "THE TERMINATOR" FOR JUST A \nDOLLAR ON THE CONDITION HE COULD DIRECT IT.',
  Oct27_2022:
    "I'VE BEEN WANTING A BABY FOR A FEW YEARS, BUT MY \nWIFE ARGUES WITH ME. SHE INSISTS ON FOREVER.",
  Oct25_2022:
    'MATTEL WOULDN\'T LICENSE BARBIE TO "TOY STORY," \nWHICH IS WHY IT INCLUDES BO PEEP INSTEAD.',
  Oct20_2022:
    "A MATHEMATICIAN SHEPHERD ROUNDED UP HIS \nFORTY-NINE SHEEP - AND THEN HE HAD FIFTY.",
  Oct18_2022:
    "OVER FOUR THOUSAND MILES LONG, THE NILE RIVER \nFLOWS THROUGH ELEVEN AFRICAN COUNTRIES.",
  Oct13_2022:
    'SCOTT FITZGERALD, A POOR SPELLER, WROTE LETTERS \nTO HIS CLOSE FRIEND "EARNEST" HEMINGWAY.',
  Oct11_2022:
    "MY BROTHER IS DEEPLY AFRAID OF NEGATIVE NUMBERS. \nHE'LL STOP AT NOTHING TO AVOID THEM.",
  Oct06_2022:
    'SOME REPARTEE ON "SESAME STREET": "ERNIE, DO YOU \nWANT TO GRAB SOME ICE CREAM?" "SURE, BERT!"',
  Oct04_2022:
    "A DEAF QUARTERBACK INVENTED THE FOOTBALL HUDDLE \nTO BLOCK HIS CALLS FROM THE OPPONENTS' VIEW.",
  Sep29_2022:
    "WHAT DO YOU GET WHEN YOU CROSS AN ELEPHANT WITH \nRHINOCEROS? GEE... ELEPHINO!",
  Sep27_2022:
    "MERCURY, THE SMALLEST PLANET IN OUR SOLAR SYSTEM, \nIS ONLY SLIGHTLY LARGER THAN EARTH'S MOON.",
  Sep22_2022:
    "SAN MARINO, MONACO, VATICAN CITY, LIECHTENSTEIN \nAND ANDORRA ARE THE ONLY NATIONS WITHOUT AIRPORTS.",
  Sep20_2022:
    'A FRIEND TOLD ME HE COULD NAME TWO STRUCTURES THAT \nHOLD WATER. I REPLIED, "WELL, DAM!"',
  Sep15_2022:
    "NINTENDO NAMED THE ICONIC MARIO AFTER A \nSEATTLE LANDLORD TO WHOM IT OWED RENT.",
  Sep13_2022:
    "I PARTICULARLY ENJOYED THE DOLPHINS WHEN I WENT \nTO SEAWORLD. FOR HOURS WE JUST CLICKED.",
  Sep08_2022:
    "MORE PEOPLE HAVE WALKED ON THE MOON (TWELVE) THAN \nHAVE BEEN BORN IN ANTARCTICA (ELEVEN).",
  Sep06_2022:
    "COPPER AND GOLD ARE THE ONLY NON-SILVERY-COLORED \nMETALS ON THE PERIODIC TABLE.",
  Sep01_2022:
    '"WAITER, WE\'D LIKE A NICE BOTTLE OF CHARDONNAY, \nPLEASE." "WHAT YEAR, SIR?" "PREFERABLY RIGHT NOW."',
  Aug30_2022:
    "SHERLOCK HOLMES HAS APPEARED IN MORE FILMS THAN ANY \nOTHER FICTIONAL CHARACTER. SECOND-MOST: DRACULA.",
  Aug25_2022:
    "I SHOULD HAVE KNOWN THE SOVIET UNION WOULDN'T \nSURVIVE. THERE WERE LOTS OF RED FLAGS.",
  Aug23_2022:
    'BY FAR THE BEST-SELLING NOVEL OF ALL TIME, "DON \nQUIXOTE" HAS SOLD OVER HALF A BILLION COPIES.',
  Aug11_2022:
    "WHAT COLOR OF STOCKINGS DO BEARS WEAR? OOH, \nTRICK QUESTION! THEY HAVE BEAR FEET.",
  Aug09_2022:
    'A ROMAN CENTURION WALKS INTO A TAVERN, RAISES TWO \nFINGERS AND SAYS, "FIVE BEERS, PLEASE."',
  Aug04_2022:
    "TODAY A JOVIAL MAN IN A CLOWN SUIT HELD A DOOR \nOPEN FOR ME. I THOUGHT, WHAT A NICE JESTER.",
  Aug02_2022:
    'EVERY SCANDAL NOWADAYS IS NICKNAMED "SOMETHING-GATE," IMPLYING THAT WATERGATE WAS ABOUT WATER.',
  Jul28_2022:
    'WHAT DID JAY-Z JOCULARLY CALL HIS GIRLFRIEND BEFORE THEIR WEDDING? HIS "FEYONCE."',
  Jul26_2022:
    "ALASKA NOT ONLY HAS THE LONGEST COASTLINE, IT HAS MORE COAST THAN EVERY OTHER STATE COMBINED.",
  Jul21_2022:
    '"ADIEU" AND "ADIOS" BOTH MEAN, LITERALLY, "TO GOD," WHILE "GOODBYE" IS SHORT FOR "GOD BE WITH YE."',
  Jul19_2022:
    "WHAT DO YOU CALL A ROCK GROUP WHOSE FOUR FAMOUS MEMBERS DON'T SING? MOUNT RUSHMORE.",
  Jul14_2022:
    "THE BOTTOM OF LAKE ERIE IS HIGHER THAN THE SURFACE OF NEARBY LAKE ONTARIO.",
  Jul07_2022:
    'THE WORD "CHECKMATE" COMES FROM THE PERSIAN "SHAH MAT," WHICH MEANS "THE KING IS DEAD."',
  Jul05_2022:
    "THE MYSTERIES OF BEST-SELLING AUTHOR AGATHA CHRISTIE HAVE SOLD WELL OVER TWO BILLION COPIES.",
  Jun30_2022:
    "MERCURY EXPERIENCES TEMPERATURE SWINGS OF OVER A THOUSAND DEGREES FAHRENHEIT.",
  Jun28_2022:
    "LIFEGUARDS WERE ABLE TO RESCUE THE DROWNING HIPPIE EVEN THOUGH HE WAS PRETTY FAR OUT.",
  Jun23_2022:
    "JUPITER'S GREAT RED SPOT IS A STORM LARGER THAN EARTH THAT HAS RAGED FOR HUNDREDS OF YEARS.",
  Jun21_2022:
    'MOVIE PREVIEWS ARE CALLED "TRAILERS" BECAUSE THEY WERE ORIGINALLY SHOWN AFTER THE FEATURE.',
  Jun16_2022:
    "I'LL ALWAYS HAVE A SPECIAL PLACE IN MY HEART FOR MY INTERVENTRICULAR SEPTUM.",
  Jun14_2022:
    "ALBANY, NEW YORK, IS THE ONLY STATE CAPITAL THAT ENDS IN ITS OWN STATE'S POSTAL ABBREVIATION.",
  Jun09_2022:
    "THE ROLLING STONES TOOK THEIR NAME FROM A SONG BY CHICAGO BLUESMAN MUDDY WATERS.",
  Jun07_2022:
    "WHEN DOES A REGULAR JOKE TURN INTO A DAD JOKE? WHEN IT BECOMES APPARENT.",
  Jun02_2022:
    'A GIANT STEEL WINDMILL DESCRIBES ITS TASTE IN ROCK MUSIC: "I\'M A BIG METAL FAN".',
  May31_2022:
    "THE HIGHEST AND LOWEST POINTS IN THE CONTINENTAL UNITED STATES ARE BOTH IN INYO COUNTY, CALIFORNIA.",
  May24_2022:
    "MISSOURI IS THE ONLY STATE THAT BORDERS AS MANY OTHER STATES AS IT HAS LETTERS IN ITS NAME.",
  May19_2022:
    "GLADIATORS IN ANCIENT ROME WERE PAID TO ENDORSE COMMERCIAL PRODUCTS.",
  May17_2022:
    "FLAMINGOS ARE PINK DUE TO PIGMENTS IN THE MICROSCOPIC ALGAE AND BRINE SHRIMP THAT THEY EAT.",
  May12_2022:
    "THE BEATLES NEARLY REUNITED AT ERIC CLAPTON'S WEDDING, WHERE ALL BUT JOHN LENNON PLAYED. ",
  May10_2022:
    "I HAVE A CRIPPLING FEAR OF ELEVATORS, SO I'VE STARTED TAKING STEPS TO AVOID THEM.",
  May05_2022:
    "WHEN WATER IS BOILED IN ZERO GRAVITY, THE VAPOR FORMS A LARGE BUBBLE AND CLINGS TO THE HEAT SOURCE.",
  May03_2022:
    "OUR VETERINARIAN HAS PUT OUR DOG ON BIRTH CONTROL. IT'S PART OF AN ANTI-LITTER CAMPAIGN.",
  Apr28_2022:
    "THE HYOID, A U-SHAPED BONE NEAR THE TONGUE, IS THE ONLY HUMAN BONE NOT CONNECTED TO ANOTHER.",
  Apr26_2022:
    "(DAD JOKE ALERT.) HOW DOES THE MAN IN THE MOON GET HIS HAIR CUT? ECLIPSE IT.",
  Apr21_2022:
    "SIX-THIRTY IS THE BEST POSSIBLE TIME ON A REGULAR ANALOG CLOCK - HANDS DOWN.",
  Apr19_2022:
    'THE WORD "ELBOW" EXISTED BEFORE SHAKESPEARE, BUT HIS IS THE FIRST KNOWN USE OF IT AS A VERB.',
  Apr14_2022:
    "RIBOFLAVIN, AN ESSENTIAL B VITAMIN, WAS ORIGINALLY CALLED LACTOCHROME AND THEN VITAMIN G.",
  Apr12_2022:
    "PLACING THE BOTTOM OF A HOT TRAY OF BROWNIES IN ICE WATER WILL MAKE THEM EXTRA RICH AND FUDGY.",
  Apr07_2022:
    "THE GREEDY LOBSTERMAN WAS ACCUSED OF PROMOTING HIS OWN SHELLFISH INTERESTS.",
  Apr05_2022:
    "THE AUDI LOGO'S FOUR RINGS REPRESENT GERMAN AUTOMAKERS THAT MERGED TO FORM ONE COMPANY.",
  Mar31_2022:
    "PHOBOS, MARS'S INNER MOON, IS A MOSTLY DARK-GRAY OBJECT SHAPED LIKE A POTATO.",
  Mar29_2022:
    "YOU WILL ALWAYS STAY YOUNG IF YOU GET EXERCISE, EAT PROPERLY AND LIE ABOUT YOUR AGE.",
  Mar15_2022:
    "AN OSCAR WINNER MAY NOT SELL A STATUETTE BEFORE OFFERING IT TO THE ACADEMY FOR A DOLLAR.",
};
